package syntax

import "regexp"
type Regexp = *regexp.Regexp
func r (pattern string) Regexp { return regexp.MustCompile(`^` + pattern) }

const LF = `\n`
const Blanks = ` \t\r　`
const Symbols = `\{\}\[\]\(\)\.\,\:\;\$#@~\?\&\|\\'"` + "`"

var EscapeMap = map [string] string {
    "_exc1":  "!",
    "_exc2":  "!!",
    "_bar1":  "|",
    "_bar2":  "||",
    "_at":    "@",
}

var Tokens = [...] Token {
    Token { Name: "String",  Pattern: r(`'[^']*'`) },
    Token { Name: "Text",    Pattern: r(`"[^"#\[\]]*"`) },
    Token { Name: "TxBegin", Pattern: r(`"[^"#\[\]]*#\[`) },
    Token { Name: "TxInner", Pattern: r(`\][^"#\[\]]*#\[`) },
    Token { Name: "TxEnd",   Pattern: r(`\][^"#\[\]]*"`) },
    Token { Name: "Comment", Pattern: r(`/\*([^\*]|[^/]|\*[^/]|[^\*]/|\*/)*\*/`) },
    Token { Name: "Comment", Pattern: r(`//[^`+LF+`]*`) },
    Token { Name: "Pragma",  Pattern: r(`#[^`+LF+`]*`) },
    Token { Name: "Blank",   Pattern: r(`[`+Blanks+`]+`) },
    Token { Name: "LF",      Pattern: r(`[`+LF+`]+`) },
    Token { Name: "Hex",     Pattern: r(`0x[0-9A-Fa-f]+`) },
    Token { Name: "Oct",     Pattern: r(`\\[0-7]+`) },
    Token { Name: "Bin",     Pattern: r(`\\\([01]+\)`) },
    Token { Name: "Exp",     Pattern: r(`\d+(\.\d+)?[Ee][\+\-]?\d+`) },
    Token { Name: "Float",   Pattern: r(`\d+\.\d+`) },
    Token { Name: "Dec",     Pattern: r(`\d+`) },
    Token { Name: "(",       Pattern: r(`\(`) },
    Token { Name: ")",       Pattern: r(`\)`) },
    Token { Name: "[",       Pattern: r(`\[`) },
    Token { Name: "]",       Pattern: r(`\]`) },
    Token { Name: "{",       Pattern: r(`\{`) },
    Token { Name: "}",       Pattern: r(`\}`) },
    Token { Name: "...",     Pattern: r(`\.\.\.`) },
    Token { Name: "..",      Pattern: r(`\.\.`) },
    Token { Name: ".",       Pattern: r(`\.`) },
    Token { Name: ",",       Pattern: r(`\,`) },
    Token { Name: "::",      Pattern: r(`\:\:`) },
    Token { Name: ":=",      Pattern: r(`\:\=`) },
    Token { Name: ":",       Pattern: r(`\:`) },
    Token { Name: ";",       Pattern: r(`\;`) },
    Token { Name: "$$",      Pattern: r(`\$$`) },
    Token { Name: "$",       Pattern: r(`\$`) },
    Token { Name: "@@",      Pattern: r(`@@`) },
    Token { Name: "@",       Pattern: r(`@`) },
    Token { Name: "??",      Pattern: r(`\?\?`) },
    Token { Name: "?",       Pattern: r(`\?`) },
    Token { Name: "~",       Pattern: r(`~`) },
    Token { Name: "&&",      Pattern: r(`\&\&`) },
    Token { Name: "&",       Pattern: r(`\&`) },
    Token { Name: "||",      Pattern: r(`\|\|`) },
    Token { Name: "|",       Pattern: r(`\|`) },
    Token { Name: `\`,       Pattern: r(`\\`) },
    Token { Name: "Name",    Pattern: r(`[^`+Symbols+Blanks+LF+`]+`) },
    //    { Name: "NoLF",    [ Inserted by Scanner ] },
    //    { Name: "Void",    [ Inserted by Scanner ] },
}

var ExtraTokens = [...] string { "NoLF", "Void" }

var ConditionalKeywords = [...] string {
    "@module", "@import", "@from",
    "@export", "@global", "@local",
    "@type", "@opaque", "@union", "@native",
    "@const", "@do",
    "@if", "@else", "@match", "@default",
    "@let", "@return",
    "@Yes", "@No",
}

var Operators = [...] Operator {}

var SyntaxDefinition = [...] string {
    "module = shebang module_name! commands",
      "shebang? = Pragma",
      "module_name = @module name!",
        "name = Name",
      "commands?  = command commands",
        "command = import | decl_type | decl_func | decl_const | do",
          "import = @import name! @from! string!",
          "do = @do expr! ;!",
    "ref = module_prefix name type_args",
      "module_prefix? = name ::",
      "type_args? = [ type! more_types ]",
        "more_types? = , type! more_types",
    "type = type_ref | type_literal",
      "type_ref = ref",
      "type_literal = repr",
    "decl_type = type_opts single_type ;! | type_opts union_type ;!",
      "type_opts = export_opt opaque_opt",
        "export_opt? = @export",
        "opaque_opt? = @opaque",
      "union_type = @union @type name! type_params { decl_type more_decl_types }",
        "more_decl_types? = decl_type more_decl_types",
      "single_type = @type name! type_params repr!",
        "type_params? = [ name! more_names ]!",
          "more_names? = , name! more_names",
        "repr = repr_tuple | repr_bundle | repr_func | repr_native",
          "repr_tuple = ( ) | ( type! more_types )!",
          "repr_bundle = { } | { field! more_fields }!",
            "field = name :! type!",
            "more_fields? = , field! more_fields",
          "repr_func = signature",
            "signature = & input_type! (! output_type! )!",
              "input_type = type",
              "output_type = type",
          "repr_native = native",
            "native = @native string",
    "decl_func = visibility name! type_params :=! [! signature! ]! body ;!",
      "visibility = @global | @local",
      "body = native | lambda!",
        "lambda = & pattern! (! expr! )!",
          "pattern = pattern_none | pattern_tuple | pattern_bundle",
            "pattern_none = name",
            "pattern_tuple = ( ) | ( name more_names )",
            "pattern_bundle = { } | { name more_names }",
    "decl_const = export_opt @const name! :=! const_value ;!",
      "const_value = native | expr!",
    "expr = casts pipe more_pipes",
      "casts? = cast casts",
        "cast = opt [ cast_type! ]!",
          "opt? = ?",
          "cast_type = ... | type",
      "pipe = term more_terms",
        "more_terms? = term more_terms",
      "more_pipes? = _bar1 pipe! more_pipes",
    "term = lambda | if | match | block | get | bundle | tuple | list | text | literal | ref",
      "if = @if term {! if_branch! more_if_branches else! }!",
        "more_if_branches? = , if_branch! more_if_branches",
        "if_branch = cond :! expr!",
          "cond = tuple | bundle",
        "else = @else :! expr!",
      "match = @match term {! match_branch! more_match_branches default }!",
        "more_match_branches? = , match_branch! more_match_branches",
        "match_branch = [ type! ]! pattern! :! expr!",
        "default? = @default :! expr!",
      "block = @let { binding! more_bindings return! }!",
        "more_bindings? = , binding! more_bindings",
        "binding = pattern := expr!",
        "return = @return expr!",
      "get = _at (! term! members! )!",
        "members? = member members",
          "member = opt . name!",
      "bundle = { } | { update pair! more_pairs }!",
        "more_pairs? = , pair! more_pairs",
        "pair = name : expr! | name",
        "update? = _at (! term! base_members )! members ,!",
          "base_members = members",
      "tuple = ( ) | ( expr! more_exprs )!",
        "more_exprs? = , expr! more_exprs",
      "list = $ ( ) | $ (! expr! more_exprs )!",
      "text = Text | TxBegin first_segment more_segments TxEnd!",
        "first_segment = segment",
          "segment = segment_tag expr!",
            "segment_tag? = name : ",
        "more_segments? = next_segment more_segments",
          "next_segment = TxInner segment",
      "literal = string | int | float | bool",
        "string = String",
        "int = Dec | Hex | Oct | Bin",
        "float = Float | Exp",
        "bool = @Yes | @No",
}
